### ISSUE TITLE
Fehlermeldung [error] Error: A 401 Unauthorized error occurred: {"error":"authorization failed"}

### ISSUE THREAD

**Issue by Wuifi** [nexx512/vitocollect#1]
Hi Jürgen,

I need your help!

What is missing to get the stuff stored in influx? 
The response of the vitocollect works pretty fine. But I still get the error message "**_Error: A 401 Unauthorized error occurred: {"error":"authorization failed"}_**"
Guess its the acces from vitocollect to influxDB.

_`[58808] Connected to vControl server
[58808] Connection to vControl successfully established
[58808] Sending command: 'getTempKist'...
[58808] Command finished.
[58808] Received response: 61.500000 Grad Celsius

[58808] Sending command: 'getTempKsoll'...
[58808] Command finished.
[58808] Received response: 52.900002 Grad Celsius

[58808] Sending command: 'getTempSpu'...
[58808] Command finished.
[58808] Received response: -0.100000 Grad Celsius

[58808] Sending command: 'getTempWWist'...
[58808] Command finished.
[58808] Received response: 56.500000 Grad Celsius

[58808] Sending command: 'getBrennerStunden1'...
[58808] Command finished.
[58808] Received response: 11500.794922 Stunden

[58808] Closing connection to vControl...
[undefined] Connection to vControl closed
Fri Mar 08 2019 22:00:18 GMT+0100 (CET) [error] Error: A 401 Unauthorized error occurred: {"error":"authorization failed"}_
`
The config.json file is the following:
`{
  "influx": {
    "host": "localhost",
    "database": "vito",
    "user": "vitocollect",
    "password": "V200KW1"
  },
  "vcontrold": {
    "host": "localhost",
    "port": 3002
  }
}
`
The jobs.json file contains this:
`
[
  {
    "measurement": "Heizungstemperaturen",
    "interval": 60000,
    "fields": {
      "Kesseltemperatur IST": {
        "type": "FLOAT",
        "command": "getTempKist"
      },
      "Kesseltemperatur SOLL": {
        "type": "FLOAT",
        "command": "getTempKsoll"
      },
      "Speichertemperatur": {
        "type": "FLOAT",
        "command": "getTempSpu"
      },
      "Warmwassertemperatur": {
        "type": "FLOAT",
        "command": "getTempWWist"
      },
      "Brennerstunden": {
        "type": "FLOAT",
        "command": "getBrennerStunden1"
      }
    }
  }
]

`
I granted all privileges to the user "vitocollect" to the influxDB "vito"
> SHOW USERS
user         admin
----         -----
vitocollect  true

Guess it's only a simple mistake I don't see...
Many thanks in advance and Thumbs up for providing the code!

**Comment by nexx512** [comment]
Sorry for the late reply. I Somehow didn't get an email about the issue.

I just checked and saw that I missed implementing the authentication.
I will look into this soon.

In the meantime, do you have a chance to use Influx without authentication?
